# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hQs1GsyXIDm5_WznrkWQ_BABQs6LVb3y
"""

import pandas as pd
import glob
import numpy as np

files = glob.glob("*.xlsx")
all_class_data = []

for file in files:
    xls = pd.ExcelFile(file)
    for sheet_name in xls.sheet_names:
        if "JAMI" in sheet_name: continue
        df = pd.read_excel(file, sheet_name=sheet_name, header=2)
        df_clean = df.iloc[:, [12, 13]].copy()
        df_clean.columns = ['Baho', 'Turi']
        df_clean = df_clean.dropna()
        df_clean['Sinf'] = sheet_name
        all_class_data.append(df_clean)

final_df = pd.concat(all_class_data, ignore_index=True)
final_df['Baho'] = pd.to_numeric(final_df['Baho'], errors='coerce')

stats = final_df.groupby'Sinf')['Baho'].agg(['mean', 'var', 'std']).reset_index()
print("--- Statistics (Dispersion) ---")
print(stats)

final_df['Z_Score'] = final_df.groupby('Sinf')['Baho'].transform(lambda x: (x - x.mean()) / x.std())
anomalies = final_df[abs(final_df['Z_Score']) > 2]
print("\n--- Anomalous Students (Risk of Subjectivity in Grading) ---")
print(anomalies)

import matplotlib.pyplot as plt

analysis = final_df.groupby('Sinf')['Baho'].agg(['mean', 'std', 'count']).reset_index()

analysis['Volatility'] = analysis['std'].fillna(0)

print(analysis)

plt.figure(figsize=(10, 6))
plt.scatter(analysis['mean'], analysis['Volatility'], s=analysis['count']*20, alpha=0.6)

for i, txt in enumerate(analysis['Sinf']):
    plt.annotate(txt, (analysis['mean'][i], analysis['Volatility'][i]), fontsize=9)

plt.title("Knowledge Quality and Volatility (Risk) Map by Class Section")
plt.xlabel("Average Grade")
plt.ylabel("Volatility (Standard Deviation)")
plt.grid(True)
plt.show()

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
stats = final_df.groupby('Sinf')['Baho'].agg(['mean', 'var', 'std', 'count']).reset_index()

final_df['Z_Score'] = final_df.groupby('Sinf')['Baho'].transform(lambda x: (x - x.mean()) / x.std())

anomalies = final_df[abs(final_df['Z_Score']) > 1.5]

print("--- Class Statistics (Dispersion - Grading Transparency) ---")
print(stats.sort_values(by='var', ascending=False))

plt.figure(figsize=(12, 6))
sns.barplot(x='Sinf', y='var', data=stats, palette='magma')
plt.title("Risk of Subjectivity in Grading (by Variance)")
plt.xticks(rotation=45)
plt.ylabel("Dispersion (Level of Difference)")
plt.show()

plt.figure(figsize=(10, 8))
sns.heatmap(final_df.pivot_table(index='Sinf', columns='Turi', values='Baho', aggfunc='count').fillna(0),
            annot=True, cmap='coolwarm')
plt.title("Distribution of Classes and Grades (Heatmap)")
plt.show()

def analyze_school_data(df):
    report = []

    avg_perf = df.groupby('Sinf')['Baho'].mean()
    top_class = avg_perf.idxmax()
    worst_class = avg_perf.idxmin()

    report.append(f"ANALYSIS REPORT (Python generated):")
    report.append(f"- Highest Achievement: {top_class} (Average: {avg_perf.max():.2f})")
    report.append(f"- Critical Point: {worst_class} (Average: {avg_perf.min():.2f})")

    variance = df.groupby('Sinf')['Baho'].var()
    risky_class = variance.idxmax()
    report.append(f"- Risk of Grading Uncertainty: {risky_class} (Variance: {variance.max():.2f})")

    return "\n".join(report)

analysis_text = analyze_school_data(final_df)
print(analysis_text)

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

features = final_df.groupbyinf')[['Baho']].mean()
scaler = StandardScaler()
scaled_data = scaler.fit_transform(features)

kmeans = KMeans(n_clusters=3, random_state=42)
features['Risk_Group'] = kmeans.fit_predict(scaled_data)

group_names = {0: 'Highly Proficient', 1: 'Critical State', 2: 'Stable Average'}
features['Status'] = features['Risk_Group'].map(group_names)

print("--- School's Artificial Intelligence Analysis: ---")
print(features)